### ISSUE TITLE
Opening notes causes crash of Evernote

### ISSUE THREAD

**Issue by agentcross** [lukaspustina/Evernote.lbaction#10]
Hi, 

since a couple of days the action does not work any more for me. The search functionality works fine but in 90% of the time trying to open a found note causes a crash of Evernote.. 
Do you experience something similar? 
I attached an exemplary error report. Let me know if you need any certain information. 

Thanks a lot, 
Christian

[Evernote Error Report.zip](https://github.com/lukaspustina/Evernote.lbaction/files/1292055/Evernote.Error.Report.zip)

**Comment by lukaspustina** [comment]
Hi.

Good to know, I haven't updated to the latest version of Evernote yet. The error report does not help me. Please send me your Evernote version and whether it's from the App Store or from Evernote's website.

**Comment by agentcross** [comment]
Evernote Version 6.12.1 (455454 App Store)

Man, I tell you, it is a pain in the ass. I already got so used to using your action, it totally disrupts my workflow now.

**Comment by lukaspustina** [comment]
I checked the release notes and didn't find anything that indicates a change in AppleScript API. Can you try the same build version, but using the app that Evernote offers on the website?

**Comment by lukaspustina** [comment]
BTW: I'm glad that the action stuck with you and that it's of any help!

**Comment by agentcross** [comment]
Just tried it... does not make a difference..

**Comment by lukaspustina** [comment]
I'm sorry to hear that. It seems 6.12 as well as 6.12.1 makes a lot ppl suffer -- see https://discussion.evernote.com/topic/108700-evernote-for-mac-6121-ga/

There's nothing I can do right now. According to the documentation, the AppleScript API did not change. And that's all I use.

My suggestion for now is to downgrade to 6.11. Here's a link for you https://cdn1.evernote.com/mac-smd/public/Evernote_RELEASE_6.11_454874.dmg. Let's sit this one out and wait for the next release. 

Keep me posted!

**Comment by agentcross** [comment]
Downgrading did the job, thanks!

**Comment by lukaspustina** [comment]
Well, at least you can work again. I'll close the issue. Let's see, if future updates fix this behavior.

**Comment by agentcross** [comment]
Hey, me again. 

Do you have any news concerning the compatibility of newer Evernote versions? 

Fianlly tried an update again to Version 6.13.1 (455785 Direkt) (Mac Version 10.12.6 (16G1114)) but still have issues and will need to go back to. 6.11

**Comment by lukaspustina** [comment]
I'm going to check that later and will come back to you.

**Comment by lukaspustina** [comment]
Hi. I just upgraded to the latest Evernote version and it turns out, that I can't search at all. Not even in the Evernote application; at least not reliably. Do you have a similar experience or is it only for the LB Action?

**Comment by agentcross** [comment]
I haven't experienced any issues with the search function of the application. But using the launchbar action still leads Evernote to crash. So I am probably going to downgrade it again.

**Comment by lukaspustina** [comment]
I just found out how to recreate the Evernote index (option click on Help, Troubleshoot, Rebuild Index) which solved my search problem and made the Launchbar Action work properly again. Please try the same.

**Comment by lukaspustina** [comment]
I have to say that I start to see random crashes of Evernote when opening a note via the Launchbar action as well.

**Comment by lukaspustina** [comment]
IMO this is a clear bug in Evernote. The AppleScript as well as the LaunchBar JavaScript run and finish correctly. Evernote does not handle the AppleScript call without crashing. This is seriously disappointing. This is at least the second time the broke AppleScript this way.

See for your self:
<img width="1418" alt="screen shot 2018-01-31 at 13 26 58" src="https://user-images.githubusercontent.com/398967/35623148-a91a02d8-068a-11e8-9c0c-464825b49692.png">

**Comment by agentcross** [comment]
Rebulding the index did not improve anyting for me. And yes it is very disappointing...

**Comment by lukaspustina** [comment]
I've upgrade to Evernote 7.0 and it runs much more stable than the last 6.x version. Especially, it seems that the troubles with AppleScript have been fix and the Launchbar integration is working properly again.
You might want to give it a shot.

**Comment by lukaspustina** [comment]
@agentcross Any news from your side regarding this behavior?

**Comment by agentcross** [comment]
I just came back from a long trip and updated to version 7.1.1 So far it seems that finally everything is working again, haven't experienced any bugs yet! 

But of course I'll let you know if something new occurs

**Comment by lukaspustina** [comment]
Perfect. Enjoy!
