### ISSUE TITLE
I've downloaded the ZIP file and deactivated the built-in Evernote integration.  What do I do now?

### ISSUE THREAD

**Issue by alexTMGH** [lukaspustina/Evernote.lbaction#11]
Sorry for the newbie question, but I'm not sure what is meant by "double click the cloned repository directory in Finder."  What exactly should I be double clicking?  Thanks in advance and apologies if this isn't the right place to be posting this.

**Comment by lukaspustina** [comment]
Hi @alexTMGH, this is the perfect place to ask.

Github appends the release number to the extracted folder name of this integration. The folder should be named 'Evernote.lbaction-0.2.0'. Just remove the the '-0.2.0' part from the folder name in Finder. The icon of the folder should change from a generic "blue" folder icon to a "yellow" Launchbar Action icon. Double clicking the latter should automatically install the Evernote integration in Launchbar.

Feel free to come back to me if you encounter any other difficulties. If you succeed, please close this ticket.
