### ISSUE TITLE
Open Evernote action spawns new window

### ISSUE THREAD

**Issue by sentience** [lukaspustina/Evernote.lbaction#12]
Following a recent update to Evernote itself, the ‘Evernote’ action (invoked without a search string) now causes a new Evernote window to open every time it is invoked. If you use it to launch Evernote when it is not running, the application launches and immediately spawns a second window.

**Comment by lukaspustina** [comment]
@sentience Hi, I can reproduce your issue. 

Re/ New window is opened: What is your expectation here? What should happen?
Re/ Two windows are opened if Evernote has not been running: That's annoying, I totally agree.

**Comment by lukaspustina** [comment]
@sentience A fix for this issue has been pushed in version 0.2.1.
