### ISSUE TITLE
Interactions have changed

### ISSUE THREAD

**Issue by robdejonge** [lukaspustina/Evernote.lbaction#13]
A few interactions are different than what seems to be described: 

- When I select the action, hit space, enter a query: I expected search results to show as a list below, but instead it does nothing. 
- When I select the action, hit space, enter a query, and hit enter: I expected the highlighted (probably first) search result to be opened, but instead an empty Evernote note window is opened. 
- When I select the action, hit space, enter a query, and hit Shift + Cmd + Enter: I expected the Evernote application to open with this search query entered and results showing, but instead it showed a list of results inside LaunchBar as per the screenshot in the `README.md`.

Or am I doing something wrong?

Running macOS 10.15.4, LaunchBar 6.12 and Evernote 7.14.

**Comment by lukaspustina** [comment]
Hi Rob,

may I assume that you have a lot of notes in Evernote?

There has been a problem with Evernote's AppleScript integrations for quite a long time now that makes the search feature very, very slow. I have around 7.000 notes and it takes 10s of seconds to get a search result when queried with my extension.

Having said that, all features work for me, once Evernote returns search results. Can you double check, if that's the same for you?

**Comment by robdejonge** [comment]
Yikes. Yes, you are right. I've got half of your notes and it took me quite a number of seconds too. Keeping in mind extended wait times, all my previous comments work as expected. That is rather disappointing of Evernote to have such poor support. Thanks for getting back to me!
