### ISSUE TITLE
Issue with search functionality for notes with '`' in titile

### ISSUE THREAD

**Issue by agentcross** [lukaspustina/Evernote.lbaction#6]
I just discovered that for any reason there is an issue with the search function. 

If I search for "spinat" (the German word for spinach btw :p) or to be precise even start entering "spi", then it does not update the suggestions at all.. nevertheless if I hit return it opens the most recent note containing the search query. 

Performing the same search request in Evernote leads 5 notes containing this word.. I have no idea if there are other letter combinations causing the same problem.

**Comment by lukaspustina** [comment]
My best guess it that processing of the search results fail and then, the return results list is empty. This manifest in "nothing" happens.

I'll add some debugging information to the processing which might shade some light on this issue; probably at the weekend.

**Comment by lukaspustina** [comment]
@agentcross Hi can you checkout the last commit I made and try to run some of the queries that yield the problem? The action should report errors to the console. It would be very helpful, if you could send me those errors for further investigations.

**Comment by agentcross** [comment]
Sure, see below. Or how would you like me to send the errors?

process launchbar:
`Evernote_Test (net.pustina.LaunchBar.action.evernote_Test): Unhandled Exception in script "suggestions.js": SyntaxError: Unexpected identifier 's'. Expected '}' to end an object literal. {
    column = 17;
    line = 12;
}`

process logger:
`Evernote LbAction failed because „item 4 of {note id "x-coredata://8595DE0B-FE6C-4F08-8659-AE2DB32B1DF6/ENNote/p21" of notebook "01 Rezepte" of application "Evernote", note id "x-coredata://8595DE0B-FE6C-4F08-8659-AE2DB32B1DF6/ENNote/p25" of notebook "01 Rezepte" of application "Evernote", note id "x-coredata://8595DE0B-FE6C-4F08-8659-AE2DB32B1DF6/ENNote/p134" of notebook "01 Rezepte" of application "Evernote"}“ kann nicht gelesen werden.`

"kann nicht gelesen werden." means " cannot be read." Don't know why it changes to German.

Hope it helps, if you need anything else just let me know.

**Comment by lukaspustina** [comment]
Perfect. What I now need is for you to send me the a screen shot of the note's retails -- if open the specific note and klick on the button represented by an `i` with a circle around it.

**Comment by agentcross** [comment]
Here you go.

![bildschirmfoto 2017-05-20 um 14 08 01](https://cloud.githubusercontent.com/assets/28731251/26275635/d66db386-3d65-11e7-9128-f8a3c6e89416.png)
![bildschirmfoto 2017-05-20 um 14 07 52](https://cloud.githubusercontent.com/assets/28731251/26275638/d6985b04-3d65-11e7-906a-cd9d7e357e55.png)
![bildschirmfoto 2017-05-20 um 14 08 13](https://cloud.githubusercontent.com/assets/28731251/26275637/d6946a76-3d65-11e7-89d5-780d5535470e.png)

**Comment by lukaspustina** [comment]
There you go. The `'` in `Oma's Spinat` cannot currently be parsed -- cf. https://github.com/lukaspustina/Evernote.lbaction#known-limitations. Unfortunately, I don't see a way how to solve this for now.

Since I'm working on your "Saved Search" feature, I will completely refactor the code -- cf. #4. Maybe I'll find another way how to deal with notes containing `'` in their title.

For now, you need to remove the `'` from the note and your search will work as expected. And you don't use the `'` in German's Genetiv as you do in English anyway :)

**Comment by agentcross** [comment]
Haha, nice German knowledge !

Thanks for investigating the bug. I did read the limitations but just thought that only this one note will be affected

**Comment by lukaspustina** [comment]
In German you say "To have tomatos on the eyes" when you mean that you have been blind for a thing. Well, I had large tomatos on mine. The issue is fixed and the limitation is gone.

**Comment by lukaspustina** [comment]
@agentcross Can you check, if the last commit fixes your "spinach problem"?

**Comment by agentcross** [comment]
Yep, is solved !
