### ISSUE TITLE
Linking notes by using launchbar

### ISSUE THREAD

**Issue by agentcross** [lukaspustina/Evernote.lbaction#7]
This is not something really urgent but rather the request for something really luxury ;-)
A feature of Evernote that I really like to use is its function to create a link within one note to another one. This allows me to easily find other relating notes. However, inserting links is always disrupting my workflow as it requires me to open Evernote's main window, find the relating note, copy its link, open the recent note again and insert the link. 

If this could be done just from the launchbar that would be make the link functionality even more helpful.

**Comment by lukaspustina** [comment]
I like the idea very much. It needs the refactoring I'm working on first though.

**Comment by lukaspustina** [comment]
Hi @agentcross. I have a preview regarding copying note links via Cmd+Return on results in branch v0.2 that you can check out. It's rough around the edges and lacks icons as well as documentation -- there is a minimalistic roadmap in the Readme#Todo section. I'll appreciate your feedback.

**Comment by agentcross** [comment]
Hi Lukas, I am really looking forward to check it out. I will be gone over the weekend and bank holiday on Monday but then I will have a look at it and will come back to you next week. 
Cheers, 
Christian

**Comment by lukaspustina** [comment]
Included in v0.2.
